[package]
name = "risc0-zkvm-sys"
version = "0.9.0"
edition = "2021"
description = "RISC Zero zero-knowledge VM system crate"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"
links = "risc0-zkvm-sys"

[lib]
path = "lib.rs"

[dependencies]
anyhow = "1.0"
cxx = "1.0"
risc0-core-sys = { version = "0.9", path = "../core" }
risc0-zkp-sys = { version = "0.9", path = "../zkp" }
risc0-zkvm-circuit-gen = { version = "0.9", path = "circuit/make-circuit" }
risc0-zkvm-circuit-sys = { version = "0.9", path = "circuit" }
tbb-sys = "1.1"

[build-dependencies]
cxx-build = "1.0"
