[package]
name = "risc0-zkvm-platform-sys"
version = "0.9.0"
edition = "2021"
description = "RISC Zero zero-knowledge VM platform crate"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"
links = "risc0-zkvm-platform-sys"

[dependencies]
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"
